This notebook could be directly excuted in google colab. The location should fit to the path variable.

In [ ]:
import numpy as np
import pandas as pd
import datetime as dt
import pathlib
import tqdm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = pathlib.Path('/content/drive/MyDrive/phase_2')

In [ ]:
txt_dirpath = path

In [ ]:
!pip install /content/drive/MyDrive/TSB-UAD-main

Processing ./drive/MyDrive/TSB-UAD-main
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Created wheel for TSB-AD: filename=TSB_AD-0.1-py3-none-any.whl size=73326 sha256=d0036d4c354f58854a112356c5c7626b74f0476c321fad8ec852dc949ca246f2
  Stored in directory: /root/.cache/pip/wheels/03/65/1b/0b7cb07eb6baea2d184373d43168a72a4137916bbd40fecaa0
Successfully built TSB-AD
  Attempting uninstall: TSB-AD
    Found existing installation: TSB-AD 0.1
    Uninstalling TSB-AD-0.1:
      Successfully uninstalled TSB-AD-0.1


In [ ]:
!pip install scikit-learn==0.23 

In [ ]:
pip install -r /content/drive/MyDrive/TSB-UAD-main/requirements.txt


     |████████████████████████████████| 902 kB 5.7 MB/s 
     |████████████████████████████████| 1.1 MB 37.6 MB/s 
     |████████████████████████████████| 1.4 MB 11.7 MB/s 
     |████████████████████████████████| 119 kB 18.1 MB/s 
     |████████████████████████████████| 781 kB 35.4 MB/s 
     |████████████████████████████████| 459 kB 33.9 MB/s 
     |████████████████████████████████| 94 kB 2.1 MB/s 
     |████████████████████████████████| 793 kB 72.6 MB/s 
     |████████████████████████████████| 830 kB 46.7 MB/s 
     |████████████████████████████████| 1.3 MB 44.0 MB/s 
     |████████████████████████████████| 38.1 MB 1.6 MB/s 
     |████████████████████████████████| 133 kB 43.6 MB/s 
     |████████████████████████████████| 822 kB 34.8 MB/s 
     |████████████████████████████████| 802 kB 44.8 MB/s 
     |████████████████████████████████| 802 kB 14.6 MB/s 
     |████████████████████████████████| 793 kB 41.2 MB/s 
     |████████████████████████████████| 793 kB 50.2 MB/s 
     |███████████

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
from TSB_AD.models.distance import Fourier
from TSB_AD.models.feature import Window
from TSB_AD.utils.slidingWindows import find_length,plotFig
from sklearn.preprocessing import MinMaxScaler


In [ ]:
from TSB_AD.models.lof import LOF


In [ ]:
results = []


In [ ]:
for txt_filepath in sorted(txt_dirpath.iterdir()):
    number = txt_filepath.stem.split('_')[0]
    number=int(number)
    X = np.loadtxt(txt_filepath)
    print(X)

    print(number)
    split = int(txt_filepath.stem.split('_')[-1])
    df=X
    max_length = len(X)
    data = df[:max_length].astype(float)
    print(data)

    slidingWindow = find_length(data)
    X_data = Window(window = slidingWindow).convert(data).to_numpy()



    data_train = data[:split]
    data_test = data[split:]



    modelName='LOF'
    clf = LOF(n_neighbors=20, n_jobs=1)
    x = X_data
    clf.fit(x)
    score = clf.decision_scores_
    score = MinMaxScaler(feature_range=(0,1)).fit_transform(score.reshape(-1,1)).ravel()
    score = np.array([score[0]]*math.ceil((slidingWindow-1)/2) + list(score) + [score[-1]]*((slidingWindow-1)//2))
    index1=np.argmax(score[split:])+split
    print(index1)
    results.append([number,index1, score])


[1990. 1996. 1958. ... 1506. 1484. 1473.]
204
[1990. 1996. 1958. ... 1506. 1484. 1473.]
14993
[1993. 2010. 1948. ... 1506. 1484. 1473.]
205
[1993. 2010. 1948. ... 1506. 1484. 1473.]
28986
[7716. 7573. 7409. ... 8075. 7880. 7729.]
206
[7716. 7573. 7409. ... 8075. 7880. 7729.]
26125
[1404. 1364. 1305. ... 1533. 1480. 1461.]
207
[1404. 1364. 1305. ... 1533. 1480. 1461.]
26968
[-708. -715. -679. ... -647. -645. -620.]
208
[-708. -715. -679. ... -647. -645. -620.]
27955
[-0.48 -0.51 -0.09 ... -0.05 -0.02  0.  ]
228
[-0.48 -0.51 -0.09 ... -0.05 -0.02  0.  ]
30136
[ 0.13  0.13  0.16 ... -0.07 -0.01 -0.03]
230
[ 0.13  0.13  0.16 ... -0.07 -0.01 -0.03]
39158
[-0.03  0.02  0.14 ...  0.65  0.66  0.62]
231
[-0.03  0.02  0.14 ...  0.65  0.66  0.62]
48963
[-0.03  0.02  0.14 ...  0.65  0.66  0.62]
232
[-0.03  0.02  0.14 ...  0.65  0.66  0.62]
48963
[0.02       0.02333333 0.01666667 ... 0.20666667 0.22333333 0.24      ]
233
[0.02       0.02333333 0.01666667 ... 0.20666667 0.22333333 0.24      ]
24455


In [ ]:
results

In [ ]:
results.to_csv('/content/drive/MyDrive/TSB-UAD-main/lof1.csv') 

In [ ]:
results = pd.DataFrame(results, columns=['number','index1','score'])


In [ ]:
res=results

In [ ]:
listdone=res['number'].tolist()

In [ ]:
results['number'] = results['number'].astype(int)


In [ ]:
results1 = pd.read_csv('drive/MyDrive/metadata.csv')

In [ ]:
df2=results1

In [ ]:
df1=results

In [ ]:
df1 = df1.set_index('number')
df1.index = pd.to_numeric(df1.index, errors='coerce')
df2 = results1.set_index('data_id')
eval = df1.join(df2).reset_index()

In [ ]:
eval

In [ ]:
for i in range (len(eval)):
    if eval.loc[i,'anomaly_start'] <= eval.loc[i,'index1'] and eval.loc[i,'index1'] <= eval.loc[i,'anomaly_end']:
        eval.loc[i,'algo_eval'] = True  

    else:
        eval.loc[i,'algo_eval'] = False

In [ ]:
eval

In [ ]:
eval["algo_eval"].value_counts()